site_name: Graphs on Grids

theme:
  name: "material"
  logo: img/logo.png

nav:
  - Home: index.md
  - Usage:
      - Workflow: usage/workflow.md
      - Model definition: usage/model_definition.md
      - Temporal layers: usage/temporal_layers.md
  - Layers:
      - Static layers: layers/static_layers.md
      - Temporal layers: layers/temporal_layers.md
  - Structure: structure.md
  - Preprocessing: preprocessing.md
  - Metrics: metrics.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            merge_init_into_class: true
  - search:
      lang: en

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML'

markdown_extensions:
  - mdx_math