site_name: Graphs on Grids

theme:
  name: "material"

nav:
  - Home: index.md
  - Layers:
      - Static layers: layers/static_layers.md
  - Structure: structure.md
  - Preprocessing: preprocessing.md
  - Metrics: metrics.md


plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            merge_init_into_class: true
  - search:
      lang: en

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML'

markdown_extensions:
  - mdx_math
  - markdown_katex